imageFolder: images
gigsFolder: gigs
outputFolder: pdf
songs:
    - nickname: song1
      image: song1.png
    - nickname: song2
      images:
        default: song2.png
        v2: song2-v2.png
    - nickname: song3
      images:
        default: song3.png
    - nickname: song4
      image: song4.png
